   version: '3.8'
   services:
     db:
       image: postgres:15
       restart: always
       environment:
         POSTGRES_DB: nba_dashboard
         POSTGRES_USER: nba_user
         POSTGRES_PASSWORD: nba_pass
       ports:
         - "5432:5432"
       volumes:
         - pgdata:/var/lib/postgresql/data
   volumes:
     pgdata: